toml
GROQ_API_KEY = "tu_clave_de_groq_aqui"
TAVILY_API_KEY = "tu_clave_de_tavily_aqui"

[app]
model = "llama3-8b-8192"
temperature = 0.2
top_p = 0.95
default_system_prompt = "You are a helpful, concise assistant."
